name: Release
on:
  push:
    branches:
      - main
      - rc
      - beta
      - alpha
      - "*.x"

jobs:
  get-next-version:
    uses: lenra-io/github-actions/.github/workflows/get-version.yml@main
    
  release:
    needs: [get-next-version]
    if: ${{ needs.get-next-version.outputs.will-release }}
    uses: lenra-io/github-actions/.github/workflows/release.yml@main
  publish:
    name: publish
    needs: [get-next-version]
    runs-on: ubuntu-latest
    env:
      VERSION: ${{ needs.get-next-version.outputs.version }}
    steps:
      - name: Checkout Code
        if: ${{ needs.get-next-version.outputs.will-release }}
        uses: actions/checkout@v3
      - name: Set version
        if: ${{ needs.get-next-version.outputs.will-release }}
        shell: bash
        run: 'sed -i -r "s/version: \"[0-9]+(\.[0-9]+){2}\"/version: \"${{ env.VERSION }}\"/g" mix.exs'
      - name: Set up Elixir
        if: ${{ needs.get-next-version.outputs.will-release }}
        uses: erlef/setup-elixir@b980a5ac9b7316a23ebc16de2bb69b7c3ad731b5
        with:
          elixir-version: "1.12" # Define the elixir version [required]
          otp-version: "24" # Define the OTP version [required]
      - name: Restore dependencies cache
        if: ${{ needs.get-next-version.outputs.will-release }}
        uses: actions/cache@v2
        with:
          path: |
            deps
            _build
          key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: ${{ runner.os }}-mix-
      - name: Publish package to hex.pm
        if: ${{ needs.get-next-version.outputs.will-release }}
        shell: bash
        run: mix hex.publish --yes
        env:
          HEX_API_KEY: ${{ secrets.HEX_API_KEY }}
